check50:
  files: &check50_files
    - !exclude "*"
    - !require virus.ipynb
  dependencies:
    - "jupyter"
    - "git+https://github.com/stgm/uva_check50.git#egg=uva.check50>=0.0.3"

submit50:
  files: *check50_files
